/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adivina_quien.clases;


import org.jpl7.Query;
import org.jpl7.Term;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class App {


    public static void main(String[] args) {
        final Opening o = new Opening();
        final Acertardo acertado=new Acertardo();
        acertado.initComponents();
        acertado.setLocationRelativeTo(null);
        Term t = Term.textToTerm("consult('C:/Users/diana/OneDrive/Documents/GitHub/AkinatorPL/Proyecto/src/examples/java/adivina_quien/clases/adivina_quien.pl')");
        Query.hasSolution(t);
        //se declara el view de Preguntar
        final Preguntas preguntasView=o.getPais_a_adivinar().getPreguntas();
        o.setVisible(true);
        o.getPais_a_adivinar().initComponents();
        o.getPais_a_adivinar().getPreguntas().initComponents();
        //Si se presiona el boton de Jugar
        o.getjButton1().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println("entro aqui");
                //se borran todos los hechos de cierto, para volver a empezar
                Query qfirst = new Query("retractall(cierto(_))");
                qfirst.hasSolution() ;
                //se borran todos los hechos de falso
                Query qfirst1 = new Query("retractall(falso(_))");
                qfirst1.hasSolution() ;
                //se inicializan los componentes
                o.getPais_a_adivinar().initComponents();
                o.getPais_a_adivinar().setLocationRelativeTo(null);
                o.getPais_a_adivinar().setVisible(true);
                preguntasView.initComponents();

            }
        });


        preguntasView.getjButton2().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String actual=preguntasView.getjLabel6().toString();
                //cada vez que se responde que si o que no a una pregunta se acerta en cierto o falso y se revisa si existe un pais que cumplen las condiciones
                //Query pais = new Query("listing(testingcosas)");
                //pais.hasSolution();
                if(preguntasView.getjLabel6().getText().contains("europeo")){
                    Query qas = new Query("assertz(cierto(continente(pais, europa)))");
                    qas.hasSolution() ;
                }
                if(preguntasView.getjLabel6().getText().contains("asiatico")){
                    Query qas = new Query("assertz(cierto(continente(pais, asia)))");
                    qas.hasSolution() ;
                }
                if(preguntasView.getjLabel6().getText().contains("oceania")){
                    Query qas = new Query("assertz(cierto(continente(pais, oceania)))");
                    qas.hasSolution() ;
                }
                if(preguntasView.getjLabel6().getText().contains("espanol")){
                    Query qas = new Query("assertz(cierto(idioma_especifico(pais, espanol)))");
                    qas.hasSolution() ;
                }
                if(preguntasView.getjLabel6().getText().contains("portugues")){
                    Query qas = new Query("assertz(cierto(idioma_especifico(pais, portugues)))");
                    qas.hasSolution() ;
                }
                if(preguntasView.getjLabel6().getText().contains("frances")){
                    Query qas = new Query("assertz(cierto(idioma_especifico(pais, frances)))");
                    qas.hasSolution() ;
                } if(preguntasView.getjLabel6().getText().contains("italiano")){
                    Query qas = new Query("assertz(cierto(idioma_especifico(pais, italiano)))");
                    qas.hasSolution() ;
                } if(preguntasView.getjLabel6().getText().contains("ingles")){
                    Query qas = new Query("assertz(cierto(idioma(pais, ingles)))");
                    qas.hasSolution() ;
                } if(preguntasView.getjLabel6().getText().contains("japones")){
                    Query qas = new Query("assertz(cierto(idioma(pais, japones)))");
                    qas.hasSolution() ;
                } if(preguntasView.getjLabel6().getText().contains("mandarin")){
                    Query qas = new Query("assertz(cierto(idioma(pais, mandarin)))");
                    qas.hasSolution();
                }
                if(preguntasView.getjLabel6().getText().contains("frio/humedo?")){
                    Query qas = new Query("assertz(cierto(clima(pais, frio_humedo)))");
                    qas.hasSolution() ;
                }
                if(preguntasView.getjLabel6().getText().contains("estaciones?")){
                    Query qas = new Query("assertz(cierto(clima(pais, estaciones)))");
                    qas.hasSolution();
                }
                if(preguntasView.getjLabel6().getText().contains("tropical?")){
                    Query qas = new Query("assertz(cierto(clima(pais, tropical)))");
                    qas.hasSolution();
                }
                if(!(preguntasView.getjLabel6().getText().contains("latin")) && preguntasView.getjLabel6().getText().contains("idioma")){
                    preguntasView.getjLabel6().setText("Este pais tiene playas?");
                }else if(preguntasView.getjLabel6().getText().contains("norte")){
                    Query qas = new Query("assertz(cierto(especifico(pais, norte)))");
                    qas.hasSolution() ;
                }else if(preguntasView.getjLabel6().getText().contains("sur")){
                    Query qas = new Query("assertz(cierto(especifico(pais, sur)))");
                    qas.hasSolution() ;
                }else if(preguntasView.getjLabel6().getText().contains("central")){
                    Query qas = new Query("assertz(cierto(especifico(pais, central)))");
                    qas.hasSolution() ;
                }else if(preguntasView.getjLabel6().getText().contains("caribe")){
                    Query qas = new Query("assertz(cierto(especifico(pais, caribe)))");
                    qas.hasSolution() ;
                }

                if(preguntasView.getjLabel6().getText().contains("america") ||
                        preguntasView.getjLabel6().getText().contains("europeo") ||
                        preguntasView.getjLabel6().getText().contains("asiatico") ||
                        preguntasView.getjLabel6().getText().contains("oceania")  ){
                    //preguntasView.getjLabel6().setText("Su clima es frio/humedo?");
                    preguntasView.getjLabel6().setText("En este pais cae nieve?");
                }else if(preguntasView.getjLabel6().getText().contains("clima")){
                    preguntasView.getjLabel6().setText("Su idioma es un idioma que desciende del latin?");
                } else if(preguntasView.getjLabel6().getText().contains("nieve")){
                    Query qas = new Query("assertz(cierto(cae_nieve(pais, nieve)))");
                    qas.hasSolution();
                    preguntasView.getjLabel6().setText("Su clima es frio/humedo?");
                }
                else if(preguntasView.getjLabel6().getText().contains("Americano?")){
                    Query qas = new Query("assertz(cierto(continente(pais, america)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Esta en america del norte?");
                }

                else if(preguntasView.getjLabel6().getText().contains("latin?")){
                    Query qas = new Query("assertz(cierto(idioma(pais, latin)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Su idioma el espanol?");
                }
                else if(preguntasView.getjLabel6().getText().contains("playas")){
                    Query qas = new Query("assertz(cierto(tiene_playa(pais, playa)))");
                    qas.hasSolution();
                    preguntasView.getjLabel6().setText("Es una isla?");
                }else if(preguntasView.getjLabel6().getText().contains("conquistador")){
                    Query qas = new Query("assertz(cierto(fue_conquistador(pais, conquistador)))");
                    qas.hasSolution();
                    preguntasView.getjLabel6().setText("Esta entre los 5 paises mas grandes del mundo?");
                }else if(preguntasView.getjLabel6().getText().contains("isla")){
                    Query qas = new Query("assertz(cierto(es_isla(pais, isla)))");
                    qas.hasSolution();

                }else if(preguntasView.getjLabel6().getText().contains("grandes")){
                    Query qas = new Query("assertz(cierto(paises_mas_grandes(pais, paises_grandes)))");
                    qas.hasSolution();
                }
                Query mira = new Query("listing(cierto)");
                System.out.println(mira.hasSolution());
                Iterator<Map<String, Term>> solutionsIter = new Query("adivina(X)");
                int cant=0;
                String solucion="";
                while (solutionsIter.hasNext()) {
                    Map<String, Term> sol = solutionsIter.next();
                    System.out.println("\t Solution found: " + sol.toString() + " mira esto "+sol.get("X").toString());
                    solucion=sol.get("X").toString();
                    cant++;
                }
                String actualAux=preguntasView.getjLabel6().toString();
                if(actual.equalsIgnoreCase(actualAux)){
                    cant++;
                }
                if(cant==1){
                    preguntasView.getjLabel6().setText("Su pais es: "+solucion);
                    Acertardo acertado=new Acertardo();
                    acertado.initComponents();
                    acertado.setLocationRelativeTo(null);
                    acertado.getjLabel10().setText("El pais elegido por el usuario fue: "+o.getPais_a_adivinar().getPais());
                    acertado.getjLabel10().setHorizontalAlignment(JLabel.CENTER);
                    System.out.println("mira el pais elegido: "+o.getPais_a_adivinar());
                   if( o.getPais_a_adivinar().getPais().equalsIgnoreCase(solucion)){
                       acertado.getjLabel6().setText("He acertado!!");
                       acertado.getjLabel8().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/happy.png")));
                    }
                   else{
                       acertado.getjLabel6().setText("No he acertado :(");
                       acertado.getjLabel8().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/sad.png")));
                   }
                    if(solucion.contains("republica")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/rd.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Republica Dominicana");
                    }else if(solucion.contains("china")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/china.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: China");
                    }else if(solucion.contains("estados")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/usa.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Estados Unidos");
                    }else if(solucion.contains("inglaterra")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/uk.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Inglaterra");
                    } else if(solucion.contains("mexico")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/mexico.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Mexico");
                    }else if(solucion.contains("japon")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/japon.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Japon");
                    }else if(solucion.contains("italia")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/italia.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Italia");
                    }else if(solucion.contains("espana")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/espania.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Espana");
                    }else if(solucion.contains("brazil")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/brazil.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Brazil");
                    }
                    acertado.setVisible(true);
                    preguntasView.setVisible(false);

                }

            }
        });
        preguntasView.getjButton1().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String actual =preguntasView.getjLabel6().toString();
                System.out.println("valor del label es: "+preguntasView.getjLabel6().getText());
                List<String> list=ciertoContenido();
                if(preguntasView.getjLabel6().getText().contains("Americano?")){
                    Query qas = new Query("assertz(falso(continente(pais, america)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Esta en el continente europeo?");
                }
                else if(preguntasView.getjLabel6().getText().contains("europeo?")){
                    preguntasView.getjLabel6().setBackground(Color.blue);
                    Query qas = new Query("assertz(falso(continente(pais, europa)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Esta en el continente asiatico?");
                }
                else if(preguntasView.getjLabel6().getText().contains("asiatico?")){
                    Query qas = new Query("assertz(falso(continente(pais, asia)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Esta en oceania?");
                }
                else if(preguntasView.getjLabel6().getText().contains("oceania?")){
                    Query qas = new Query("assertz(falso(continente(pais, oceania)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Usted no ha elegido ningun continente.");
                }
                else if(preguntasView.getjLabel6().getText().contains("norte?")){
                    Query qas = new Query("assertz(falso(especifico(pais, norte)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Esta en america del sur?");
                }
                else if(preguntasView.getjLabel6().getText().contains("sur?")){
                    Query qas = new Query("assertz(falso(especifico(pais, sur)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Esta en america central?");
                }
                else if(preguntasView.getjLabel6().getText().contains("central?")){
                    Query qas = new Query("assertz(falso(especifico(pais, central)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Esta en america: el caribe?");
                }
                if(preguntasView.getjLabel6().getText().contains("frio/humedo?")){
                    Query qas = new Query("assertz(falso(clima(pais, frio_humedo)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Tiene un clima acorde a las estaciones?");
                }
                else if(preguntasView.getjLabel6().getText().contains("estaciones?")){
                    Query qas = new Query("assertz(falso(clima(pais, estaciones)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Tiene un clima tropical?");
                }else if(preguntasView.getjLabel6().getText().contains("nieve?")){
                    Query qas = new Query("assertz(falso(cae_nieve(pais, nieve)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("El clima de este pais es frio/humedo?");
                }
                else if(preguntasView.getjLabel6().getText().contains("espanol?")){
                    Query qas = new Query("assertz(falso(idioma_especifico(pais, espanol)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Su idioma es el frances?");
                }else if(preguntasView.getjLabel6().getText().contains("frances?")){
                    Query qas = new Query("assertz(falso(idioma_especifico(pais, frances)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Su idioma es el portugues?");
                }else if(preguntasView.getjLabel6().getText().contains("portugues?")){
                    Query qas = new Query("assertz(falso(idioma_especifico(pais, portugues)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Su idioma es el italiano?");
                }
                else if(preguntasView.getjLabel6().getText().contains("latin?")){
                    Query qas = new Query("assertz(falso(idioma(pais, latin)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Su idioma es el ingles?");
                }else if(preguntasView.getjLabel6().getText().contains("ingles?")){
                    Query qas = new Query("assertz(falso(idioma(pais, ingles)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Su idioma es el japones?");
                }
                else if(preguntasView.getjLabel6().getText().contains("japones?")){
                    Query qas = new Query("assertz(falso(idioma(pais, japones)))");
                    qas.hasSolution() ;
                    preguntasView.getjLabel6().setText("Su idioma es el mandarin?");
                }
                else if(preguntasView.getjLabel6().getText().contains("playas")){
                    Query qas = new Query("assertz(falso(tiene_playa(pais, playa)))");
                    qas.hasSolution();
                    preguntasView.getjLabel6().setText("Es una isla?");
                }else if(preguntasView.getjLabel6().getText().contains("isla")){
                    Query qas = new Query("assertz(falso(es_isla(pais, isla)))");
                    qas.hasSolution();
                    preguntasView.getjLabel6().setText("El pais es conquistador?");
                }else if(preguntasView.getjLabel6().getText().contains("conquistador")){
                    Query qas = new Query("assertz(falso(fue_conquistador(pais, conquistador)))");
                    qas.hasSolution();
                    preguntasView.getjLabel6().setText("Esta entre los 5 paises mas grandes del mundo?");
                }
                Query mira = new Query("listing(cierto)");
                System.out.println(mira.hasSolution());
                Iterator<Map<String, Term>> solutionsIter = new Query("adivina(X)");
                int cant=0;
                String solucion="";
                while (solutionsIter.hasNext()) {
                    Map<String, Term> sol = solutionsIter.next();
                    System.out.println("\t Solution found: " + sol.toString() + " mira esto "+sol.get("X").toString());
                    solucion=sol.get("X").toString();
                    cant++;
                }
                String actualAux=preguntasView.getjLabel6().toString();
                if(actual.equalsIgnoreCase(actualAux)){
                    cant++;
                }
                if(cant==1){
                    preguntasView.getjLabel6().setText("Su pais es: "+solucion);

                    acertado.getjLabel10().setText("El pais elegido por el usuario fue: "+o.getPais_a_adivinar().getPais());
                    acertado.getjLabel10().setHorizontalAlignment(JLabel.CENTER);
                    System.out.println("mira el pais elegido: "+o.getPais_a_adivinar());
                    if( o.getPais_a_adivinar().getPais().equalsIgnoreCase(solucion)){
                        acertado.getjLabel6().setText("He acertado!!");
                        acertado.getjLabel8().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/happy.png")));
                    }
                    else{
                        acertado.getjLabel6().setText("No he acertado :(");
                        acertado.getjLabel8().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/sad.png")));
                    }
                    if(solucion.contains("republica")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/rd.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Republica Dominicana");
                    }else if(solucion.contains("china")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/china.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: China");
                    }else if(solucion.contains("estados")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/usa.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Estados Unidos");
                    }else if(solucion.contains("inglaterra")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/uk.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Inglaterra");
                    } else if(solucion.contains("mexico")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/mexico.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Mexico");
                    }else if(solucion.contains("japon")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/japon.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Japon");
                    }else if(solucion.contains("italia")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/italia.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Italia");
                    }else if(solucion.contains("espana")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/espania.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Espana");
                    }else if(solucion.contains("brazil")){
                        acertado.getjLabel5().setIcon(new javax.swing.ImageIcon(getClass().getResource("img/brazil.png")));
                        acertado.getjLabel9().setText("El pais adivinado fue: Brazil");
                    }
                    acertado.setVisible(true);
                    preguntasView.setVisible(false);
                }

            }
        });
        System.out.println("MIRA SKDFJHKJDAS: " +acertado.getjButton1().getText());



    }

    private static List<String> ciertoContenido() {

        return null;
    }


}

