/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adivina_quien.clases;

import adivina_quien.clases.Opening;

import javax.swing.*;

/**
 *
 * @author saby_
 */
public class Pais_a_adivinar extends javax.swing.JFrame {
    private Preguntas preguntas;
    private String pais;


    /**
     * Creates new form UI
     */
    public Pais_a_adivinar() {
        initComponents();
        setTitle("Adivina Quién?!!");
        setLocationRelativeTo(null);
        //Opening o = new Opening();
        this.preguntas=new Preguntas();
    }

    public String getPais() {
        return pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    public void initComponents() {
        System.out.println("INIT COMPONETS");
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        italia_ = new javax.swing.JButton();
        japon_ = new javax.swing.JButton();
        brazil_ = new javax.swing.JButton();
        china_ = new javax.swing.JButton();
        espania_ = new javax.swing.JButton();
        mexico_ = new javax.swing.JButton();
        rd_ = new javax.swing.JButton();
        usa_ = new javax.swing.JButton();
        uk_ = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/Vector.png"))); // NOI18N
        jLabel1.setText("Edición Paises");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Adivina Quién");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("?");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("¿");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Elige el pais que quieres que adivine");

        italia_.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/italia.png"))); // NOI18N
        italia_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italia_ActionPerformed(evt);
            }
        });

        japon_.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/japon.png"))); // NOI18N
        japon_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japon_ActionPerformed(evt);
            }
        });

        brazil_.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/brazil.png"))); // NOI18N
        brazil_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brazil_ActionPerformed(evt);
            }
        });

        china_.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/china.png"))); // NOI18N
        china_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                china_ActionPerformed(evt);
            }
        });

        espania_.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/espania.png"))); // NOI18N
        espania_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espania_ActionPerformed(evt);
            }
        });

        mexico_.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/mexico.png"))); // NOI18N
        mexico_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mexico_ActionPerformed(evt);
            }
        });

        rd_.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/rd.png"))); // NOI18N
        rd_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_ActionPerformed(evt);
            }
        });

        usa_.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/usa.png"))); // NOI18N
        usa_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usa_ActionPerformed(evt);
            }
        });

        uk_.setIcon(new javax.swing.ImageIcon(getClass().getResource("img/uk.png"))); // NOI18N
        uk_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uk_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(268, 268, 268)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel2)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jLabel3))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(37, 37, 37)
                                                                                .addComponent(jLabel1))))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(189, 189, 189)
                                                                .addComponent(italia_))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(116, 116, 116)
                                                                .addComponent(espania_)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(3, 3, 3)
                                                                .addComponent(mexico_)
                                                                .addGap(54, 54, 54)
                                                                .addComponent(rd_)
                                                                .addGap(63, 63, 63)
                                                                .addComponent(usa_)
                                                                .addGap(73, 73, 73)
                                                                .addComponent(uk_))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(67, 67, 67)
                                                                .addComponent(japon_)
                                                                .addGap(76, 76, 76)
                                                                .addComponent(brazil_)
                                                                .addGap(54, 54, 54)
                                                                .addComponent(china_)))))
                                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(italia_)
                                        .addComponent(japon_)
                                        .addComponent(brazil_)
                                        .addComponent(china_))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(espania_)
                                        .addComponent(mexico_)
                                        .addComponent(rd_)
                                        .addComponent(usa_)
                                        .addComponent(uk_))
                                .addContainerGap(199, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>


    private void italia_ActionPerformed(java.awt.event.ActionEvent evt) {
        this.preguntas.setVisible(true);
        this.preguntas.setLocationRelativeTo(null);
        this.setVisible(false);
        this.pais="italia";
    }

    private void japon_ActionPerformed(java.awt.event.ActionEvent evt) {
        this.preguntas.setVisible(true);
        this.preguntas.setLocationRelativeTo(null);
        this.setVisible(false);this.preguntas.setVisible(true);
        this.pais="japon";
    }

    private void brazil_ActionPerformed(java.awt.event.ActionEvent evt) {
        this.preguntas.setVisible(true);
        this.preguntas.setLocationRelativeTo(null);
        this.setVisible(false);
        this.pais="brazil";
    }

    private void china_ActionPerformed(java.awt.event.ActionEvent evt) {
        this.preguntas.setVisible(true);
        this.preguntas.setLocationRelativeTo(null);
        this.setVisible(false);
        this.pais="china";
    }

    private void mexico_ActionPerformed(java.awt.event.ActionEvent evt) {
        //this.preguntas.setVisible(true);
        this.preguntas.setVisible(true);
        this.preguntas.setLocationRelativeTo(null);
        this.setVisible(false);
        this.pais="mexico";
    }

    private void espania_ActionPerformed(java.awt.event.ActionEvent evt) {
        this.preguntas.setVisible(true);
        this.preguntas.setLocationRelativeTo(null);
        this.setVisible(false);
        this.pais="espana";
    }

    private void rd_ActionPerformed(java.awt.event.ActionEvent evt) {
        this.preguntas.setVisible(true);
        this.preguntas.setLocationRelativeTo(null);
        this.setVisible(false);
        this.pais="republica_dominicana";
    }

    private void usa_ActionPerformed(java.awt.event.ActionEvent evt) {
        this.preguntas.setVisible(true);
        this.preguntas.setLocationRelativeTo(null);
        this.setVisible(false);
        this.pais="estados_unidos";
    }

    private void uk_ActionPerformed(java.awt.event.ActionEvent evt) {
        this.preguntas.setVisible(true);
        this.preguntas.setLocationRelativeTo(null);
        this.setVisible(false);
        this.pais="inglaterra";
    }

    public Preguntas getPreguntas() {
        return preguntas;
    }

    public void setPreguntas(Preguntas preguntas) {
        this.preguntas = preguntas;
    }

    public JButton getBrazil_() {
        return brazil_;
    }

    public void setBrazil_(JButton brazil_) {
        this.brazil_ = brazil_;
    }

    public JButton getChina_() {
        return china_;
    }

    public void setChina_(JButton china_) {
        this.china_ = china_;
    }

    public JButton getEspania_() {
        return espania_;
    }

    public void setEspania_(JButton espania_) {
        this.espania_ = espania_;
    }

    public JButton getItalia_() {
        return italia_;
    }

    public void setItalia_(JButton italia_) {
        this.italia_ = italia_;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JButton getJapon_() {
        return japon_;
    }

    public void setJapon_(JButton japon_) {
        this.japon_ = japon_;
    }

    public JButton getMexico_() {
        return mexico_;
    }

    public void setMexico_(JButton mexico_) {
        this.mexico_ = mexico_;
    }

    public JButton getRd_() {
        return rd_;
    }

    public void setRd_(JButton rd_) {
        this.rd_ = rd_;
    }

    public JButton getUk_() {
        return uk_;
    }

    public void setUk_(JButton uk_) {
        this.uk_ = uk_;
    }

    public JButton getUsa_() {
        return usa_;
    }

    public void setUsa_(JButton usa_) {
        this.usa_ = usa_;
    }

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {

        final Opening o = new Opening();//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        Preguntas p = new Preguntas();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pais_a_adivinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pais_a_adivinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pais_a_adivinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pais_a_adivinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pais_a_adivinar().setVisible(true);
                o.setVisible(false);
            }
        });
    }*/

    // Variables declaration - do not modify
    private javax.swing.JButton brazil_;
    private javax.swing.JButton china_;
    private javax.swing.JButton espania_;
    private javax.swing.JButton italia_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton japon_;
    private javax.swing.JButton mexico_;
    private javax.swing.JButton rd_;
    private javax.swing.JButton uk_;
    private javax.swing.JButton usa_;
    // End of variables declaration
}
